### ISSUE TITLE
Docker AUTO Reload on code changes

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-corporate-dashboard#1]
> Enhancement asked in support (Discord)

**Comment by app-generator** [comment]
Hello @sgnd 

Here is the latest `error log` for Windows 11, WSL2

```log
PS D:\work\tests\django-corporate-dashboard> docker container kill $(docker ps -q) ; docker container rm $(docker ps -a -q) ; docker network prune -f ;  docker-compose up --build
3e18f9808a77
211c3c4a8cee
3e18f9808a77
211c3c4a8cee
Deleted Networks:
django-corporate-dashboard_web_network
django-corporate-dashboard_db_network

Creating network "django-corporate-dashboard_db_network" with driver "bridge"
Creating network "django-corporate-dashboard_web_network" with driver "bridge"
Building appseed-app
[+] Building 4.7s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                        0.0s
 => => transferring dockerfile: 456B                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.9                                                                                                                                               1.5s
 => [internal] load build context                                                                                                                                                                           0.3s
 => => transferring context: 20.50MB                                                                                                                                                                        0.3s
 => [1/8] FROM docker.io/library/python:3.9@sha256:603ac689b89c2a59791a4e7cd3d727f2a673ac3df02dabbd97b0d85bb1eca4e7                                                                                         0.0s
 => CACHED [2/8] WORKDIR /app                                                                                                                                                                               0.0s
 => CACHED [3/8] COPY requirements.txt .                                                                                                                                                                    0.0s
 => CACHED [4/8] RUN pip install --upgrade pip                                                                                                                                                              0.0s
 => CACHED [5/8] RUN pip install --no-cache-dir -r requirements.txt                                                                                                                                         0.0s
 => [6/8] COPY . .                                                                                                                                                                                          0.1s
 => [7/8] RUN chmod +x /app/entrypoint.sh                                                                                                                                                                   0.4s
 => [8/8] RUN python manage.py migrate                                                                                                                                                                      2.1s
 => exporting to image                                                                                                                                                                                      0.2s
 => => exporting layers                                                                                                                                                                                     0.2s
 => => writing image sha256:fd07b923e1ee8de8925599f3311684b3089a3f3116a4f98cdf1245bf565a69a6                                                                                                                0.0s
 => => naming to docker.io/library/django-corporate-dashboard_appseed-app                                                                                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Creating appseed_app ... done
Creating nginx       ... done
Attaching to appseed_app, nginx
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
nginx          | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx          | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx          | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx          | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx          | 2023/05/28 10:37:16 [notice] 1#1: using the "epoll" event method
nginx          | 2023/05/28 10:37:16 [notice] 1#1: nginx/1.23.2
nginx          | 2023/05/28 10:37:16 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
nginx          | 2023/05/28 10:37:16 [notice] 1#1: OS: Linux 5.15.90.1-microsoft-standard-WSL2
nginx          | 2023/05/28 10:37:16 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker processes
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 20
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 21
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 22
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 23
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 24
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 25
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 26
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 27
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 28
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 29
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 30
nginx          | 2023/05/28 10:37:16 [notice] 1#1: start worker process 31
appseed_app exited with code 126
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app    | bash: /app/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
appseed_app exited with code 126
appseed_app exited with code 126
Exception in thread Thread-7:
Traceback (most recent call last):
  File "docker\api\client.py", line 268, in _raise_for_status
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.41/containers/61a11e4dbee88f77a66c8d76104d2e11d4676bea3d6a2f27b9e214145675590e/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 950, in _bootstrap_inner
  File "threading.py", line 888, in run
  File "compose\cli\log_printer.py", line 224, in watch_events
  File "compose\container.py", line 202, in attach_log_stream
  File "compose\container.py", line 294, in attach
  File "docker\utils\decorators.py", line 19, in wrapped
  File "docker\api\container.py", line 62, in attach
  File "docker\api\client.py", line 405, in _read_from_socket
  File "docker\api\client.py", line 318, in _get_raw_response_socket
  File "docker\api\client.py", line 270, in _raise_for_status
  File "docker\errors.py", line 19, in create_api_error_from_http_exception
  File "requests\models.py", line 881, in json
  File "requests\models.py", line 829, in content
  File "requests\models.py", line 751, in generate
  File "urllib3\response.py", line 575, in stream
  File "urllib3\response.py", line 518, in read
  File "http\client.py", line 458, in read
  File "http\client.py", line 502, in readinto
  File "docker\transport\npipesocket.py", line 211, in readinto
  File "docker\transport\npipesocket.py", line 20, in wrapped
RuntimeError: Can not reuse socket after connection was closed.

````

**Comment by app-generator** [comment]
Having hot reaload on templates & assets seems hard to achieve it. 
Ty for your effort @sgnd  

Let's consider the delivery done.

**Comment by surenjanath** [comment]
it works perfectly !!

**Comment by app-generator** [comment]
Validated in [v1.0.4](https://github.com/app-generator/django-corporate-dashboard/releases).
Closing.
